apiVersion: v1
kind: Service
metadata:
  name: slack-integration-service
  namespace: default
spec:
  selector:
    app: slack-integration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP